"""add invitation comment

Revision ID: 394e671a69d6
Revises: 3a47b6f2ea14
Create Date: 2026-09-23 20:03:44.147730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '394e671a69d6'
down_revision: Union[str, None] = '3a47b6f2ea14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('comment', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'comment')
    # ### end Alembic commands ###
