"""add event location details and maps link

Revision ID: a34621deec80
Revises: 581ef36e8d18
Create Date: 2026-09-23 18:08:27.619135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34621deec80'
down_revision: Union[str, None] = '581ef36e8d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('location_details', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('maps_link', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'maps_link')
    op.drop_column('events', 'location_details')
    # ### end Alembic commands ###
